version: '{build}'
environment:
  MyGetApiKey:
    secure: gZPBkuTOssW7pLkg5qibqndC/gFOjsJvym6vzbgsxf/vLZb13ewQKfiD6gGmLXJj
configuration: Release
platform: Any CPU
build_script:
- cmd: build.cmd
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
test: off
deploy: off
